
server:
  port: 8081



jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ht_htzk
  username: root
  password: maxwell
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 30000